name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build satfreq.json
      run: rm .gitignore && python3 concatenate.py

    - name: Upload satfreq.json
      uses: actions/upload-artifact@v3
      with:
        name: satfreq
        path: satfreq.json

    - name: Generate json/ directory listing
      run: |
        cd json &&
        (echo '<!DOCTYPE html><html><body><ul><li><a href="..">..</a></li>'
        for i in *; do
            if [ "$i" != "index.html" ]; then
                echo "<li><a href=\"$i\">$i</a></li>"
            fi
        done
        echo '</ul></body></html>') > index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
