name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build satfreq.json
      run: python3 concatenate.py && mkdir data && mv satfreq.json data

    - name: Upload satfreq.json
      uses: actions/upload-artifact@v3
      with:
        name: satfreq
        path: data/satfreq.json

    - name: Generate json/ directory listing
      run: cd json && (echo '<!DOCTYPE html><html><body><ul>'; for i in *; do echo "<li><a href=\"$i\">$i</a></li>"; done; echo '</ul></body></html>') > index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
