name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build satfreq.json
      run: rm .gitignore && python3 concatenate.py

    - name: Build bookmark files
      run: |
        python3 sdrpp_bookmarks.py &&
        python3 sdrsharp_bookmarks.py &&
        python3 gqrx_bookmarks.py &&
        mkdir bookmarks &&
        mv sdrpp_bookmarks.json   bookmarks/sdrpp.json &&
        mv sdrsharp_bookmarks.xml bookmarks/sdrsharp.xml &&
        mv gqrx_bookmarks.csv     bookmarks/gqrx.csv

    - name: Upload bookmarks
      uses: actions/upload-artifact@v3
      with:
        name: bookmarks
        path: bookmarks/

    - name: Upload satfreq.json
      uses: actions/upload-artifact@v3
      with:
        name: satfreq
        path: satfreq.json

    - name: Generate directory listings
      run: cd json && ../make_html_listing.sh && cd ../bookmarks && ../make_html_listing.sh

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
